syntax = "proto3";

package kusai.service.proto.textchain.v1;

message CreateRequest {
  uint32 markov_id = 1;
  uint32 tokenizer_id = 2;
}

message CreateResponse {
  uint32 textchain_id = 1;
}

message DeleteRequest {
  uint32 textchain_id = 1;
}

message DeleteResponse {
  bool success = 1;
}

message TrainRequest {
  uint32 textchain_id = 1;
  repeated string sequences = 2;
}

message TrainResponse {
  bool success = 1;
}

message GenerateSequenceRequest {
  uint32 textchain_id = 1;
  string context = 2;
  optional uint32 limit = 3;
}

message GenerateSequenceResponse {
  repeated uint64 tokens = 1;
}

message GenerateTextRequest {
  uint32 textchain_id = 1;
  string context = 2;
  optional uint32 limit = 3;
}

message GenerateTextResponse {
  string text = 1;
}

service TextChainService {
  rpc Create(CreateRequest) returns (CreateResponse);
  rpc Delete(DeleteRequest) returns (DeleteResponse);

  rpc Train(TrainRequest) returns (TrainResponse);
  rpc GenerateSequence(GenerateSequenceRequest) returns (GenerateSequenceResponse);
  rpc GenerateText(GenerateTextRequest) returns (GenerateTextResponse);
}
