syntax = "proto3";

package kusai.service.proto.markov.v1;

message CreateRequest {
  uint32 graph_id = 1;

  message SimpleConfig {}

  message NGramConfig {
    uint32 context_size = 1;
  }

  message BackoffConfig {
    uint32 max_context_size = 1;
  }

  oneof impl {
    SimpleConfig simple = 2;
    NGramConfig ngram = 3;
    BackoffConfig backoff = 4;
  }
}

message CreateResponse {
  uint32 markov_id = 1;
}

message DeleteRequest {
  uint32 markov_id = 1;
}

message DeleteResponse {
  bool success = 1;
}

service MarkovService {
  rpc Create(CreateRequest) returns (CreateResponse);
  rpc Delete(DeleteRequest) returns (DeleteResponse);
}
