syntax = "proto3";

package kusai.service.proto.tokenizer.v1;

message CreateRequest {
  message SimpleConfig {}

  oneof impl {
    SimpleConfig simple = 1;
  }
}

message CreateResponse {
  uint32 tokenizer_id = 1;
}

message DeleteRequest {
  uint32 tokenizer_id = 1;
}

message DeleteResponse {
  bool success = 1;
}

message EncodeRequest {
  uint32 tokenizer_id = 1;
  string text = 2;
}

message EncodeResponse {
  repeated uint64 tokens = 1;
}

message DecodeRequest {
  uint32 tokenizer_id = 1;
  repeated uint64 tokens = 2;
}

message DecodeResponse {
  string text = 1;
}

service TokenizerService {
  rpc Create(CreateRequest) returns (CreateResponse);
  rpc Delete(DeleteRequest) returns (DeleteResponse);

  rpc Encode(EncodeRequest) returns (EncodeResponse);
  rpc Decode(DecodeRequest) returns (DecodeResponse);
}
